version: '3'
services:
  dev:
    image: bootcamp:latest
    build:
     context: .
     dockerfile: .dockerfile
    volumes:
      - ./source_code:/root/code
      - ./.vscode-server:/root/.vscode-server

     